#!/usr/bin/env python
# coding: utf-8
import time
import RPi.GPIO as GPIO
import numpy as  np
from RPLCD import CharLCD,cleared


#program for the IR sensor(using raspberrypi)
ir_sensor = 16
display = 18
signal_red = 24
signal_yellow=22
signal_green=5
lcd = CharLCD(cols=16, rows=2, pin_rs=37, pin_e=35, pins_data=[40, 38, 36, 32, 33, 31, 29, 23],numbering_mode=GPIO.BOARD)
GPIO.setmode(GPIO.BOARD)
GPIO.setup(signal_red,GPIO.IN)
GPIO.setup(signal_yellow,GPIO.IN)
GPIO.setup(signal_green,GPIO.IN)
GPIO.setup(ir_sensor,GPIO.IN)

with cleared(lcd):
    lcd.write_string(u'IR Sensor ready!')

try: 
    if GPIO.input(signal_red or signal_yellow):
        while True:
            if GPIO.input(ir_sensor):
                status=1;
                with cleared(lcd):
                    lcd.write_string(u'vechile detected!')
                while GPIO.input(ir_sensor):
                    time.sleep(0.2)
            else:
                status=0;
                GPIO.output(display,False)
    else pass

except KeyboardInterrupt:
    GPIO.cleanup()

